version: "3.9"
services:
  redis:
        image: redis:7-alpine
        ports:
          - "6379:6379" 

  # postgres:
  #         image: postgres:15-alpine
  #         environment: 
  #             POSTGRES_USER: dispatcher
  #             POSTGRES_PASSWORD: dispatcher
  #             POSTGRES_DB:  notification-dispatcher
  #         ports:
  #           - "5432:5432"